### ISSUE TITLE
Adicionar um arquivo LICENSE no repositório

### ISSUE THREAD

**Issue by rimolive** [Guilherme-Silveira/bigdata-docker#1]
Guilherme,

Pretendo fazer uma simplificação da sua arquitetura tomando a sua como ponto de partida, mas quero dar-lhe o devido crédito à sua implementação. Por isso estou abrindo essa issue para que adicione uma licença no seu repo de forma que eu possa preservar o seu trabalho.

Minha sugestão para licença é o MIT: http://escolhaumalicenca.com.br/licencas/mit/

Porém, fique à vontade para escolher uma licença mais apropriada.

**Comment by Guilherme-Silveira** [comment]
Mil desculpas pela demora. Eu nem tinha me atentado a essa issue. Eu criei o arquivo de license seguindo sua recomendação. Muito obrigado e espero que esse projeto possa ter contribuído de alguma forma para você.
